### ISSUE TITLE
Not updating view correctly when switch between testspecs

### ISSUE THREAD

**Issue by ShawnMcKee** [perfsonar/meshconfig-admin#26]
I just observed a small problem on meshconfig.grid.iu.edu.     I was viewing Testspecs and looking at the USATLAS Traceroute details.  I then click on USCMS Latency and see the fields Bucket Width and Sample Count are empty.   If I then click on USATLAS Latency I see values.   If I *then* click back on USCMS Latency I also see values.  The values seem to be there but not shown depending upon the order I view things.

My browser is Chrome on Windows 10  Version 57.0.2987.133

Shawn

PS: Actually I am *not* sure the values are there.   The current ps-testbed, us-atlas and us-cms meshes were created/imported from meshconfig-itb.grid.iu.edu.   The us-cms mesh seems to have missing data?
I still see differences (as I reported above) depending upon the order I view Testspecs.  

Shawn

**Comment by soichih** [comment]
Shawn, 

Thank you for reporting this issue. This was affecting all service types, and caused by string field sent to numeric field (myosg meshconfig used to publish all numeric fields as string) and angular throwing exception.

I will test the fix on meshconfig-itb and ask Marina to update the production instance.

**Comment by apertome** [comment]
I believe this one is also fixed, can @ShawnMcKee comment on this?

**Comment by ShawnMcKee** [comment]
Yes, Soichi's fix and the redeploy resolved this.

Shawn
