### ISSUE TITLE
Determine whether to serve up new psconfig format or old meshconfig format

### ISSUE THREAD

**Issue by apertome** [perfsonar/meshconfig-admin#42]
In the publisher, we need to figure out a way to determine which format to serve up. We could have separate URLs, run separate publishers, or try detecting the HTTP user agent.

**Comment by apertome** [comment]
Dan suggested we have psconfig append a parameter to the URL to request psconfig format, rather than trying to detect.

He also pointed out that user agent is probably going to show up just as LWP for both meshconfig and psconfig cases. Unless that's been customized.

**Comment by arlake228** [comment]
We have full control over what psconfig sets as the useragent, so there is no issue with everything looking the same. I don't like the idea of pSConfig auto-appending any get parameters since it's going to have no way of knowing if something came from the GUI or not...and if we did find a way it'd probably be hacky and oddly specific.

The easiest route is to just serve up the old meshconfig format by default, and someone can optionally set the GET parameter if they want pSConfig. The pSConfig agents can read both formats, so it doesn't much matter which one it gets. This means existing clients will still be reading the old format when they update which is fine. If someone explicitly wants pSConfig format they will have to go in and update there URL with the parameter. Probably in 4.2 after people have had a chance to update and 4.0 is EOL, we can flip this so pSConfig is the default. 

If we add any pSConfig specific features (like the ability to add non-esmond archives) in the interim you will likely need to add some intelligence into the code to only serve-up pSConfig since meshconfig will not be possible.

**Comment by apertome** [comment]
After some more discussion we decided to do this with query strings, like:
` /pub/config/meshname?format=psconfig`
